# PureKitPvP by LifelessNerd
# Made to work with PureKits kit files
# 2022 - 2023

# World in which the plugin should be active: i.e. kits, deaths, stats and such
world: pvp

# Clear inventory after player is killed (EXPERIMENTAL when setting this to false, not sure what consequences it has!)
inventory-clear: true

#Quick kill when falling in void, only works when suicide-command is enabled
quick-voidkill: true

# Remove any blocks that people in survival/adventure place in your pvp world after a set time
remove-blocks: true

# If above true, delay in seconds after which blocks should automatically be removed
remove-blocks-delay: 30

#If above true, Y level at which you should die in pvp, please provide double (something like 0.0 or -10.0)
voidY: 0.0

#respawn X, Y, Z in world, this is basically the spawn region
respawnX: 0.5
respawnY: 142.0
respawnZ: 0.5

# Spawn region radius; you won't get fall damage in this area (square area relative to respawnX and respawnZ)
spawn-radius: 6

#Whether people who get a kill streak will get glowing effect
killstreak-glowing: true
#If above true, the duration in seconds
killstreak-glowing-duration: 100

#Suicide command from PureKitPvP, ensures death recaps work correctly
suicide-command: true

# Whether the level of the player should be displayed in front of the message as prefix  (only in the enabled world)
level-chat: true

#In loottables, tell the player they got lucky if the drop was below or equal to this percentage
loottable-message-percentage: 1

#Notoriety perk boundary
#If the notoriety perk is too OP, restrict the maximum level of sharpness that can be gained
#Set to -1 if infinite
notoriety-maximum: -1

#Marksman perk boundary
#If the marksman perk is too OP, restrict the maximum level of power that can be gained
#Set to -1 if infinite
marksman-maximum: -1

#Default kill effect
default-kill-effect: "firework"

#Default projectile trail
default-projectile-trail: "none"

# Projectile trail period delay
# The amount of time between each particle, in ticks (20 ticks = 1 particle per second)
projectile-trail-period: 1

# Projectile trail count
# Amount of particles per spawn (also controlled by projectile-trail-period)
projectile-trail-count: 5

# Chicken prevention: kits with eggs might spawn chicken; when this is true they are prevented from spawning
chicken-prevention: true

# Global Kit PvP combat event loop
# enabled?
global-event-loop: true

# Seconds between global combat events - events themselves have different times (see below)
global-event-period: 10

# Events that occur in global combat event loop
global-events-enabled: ["TeleMadness","Pickup Frenzy"]

# Event lengths in seconds
telemadness-length: 10
pickup-frenzy-length: 10
juggernaut-length: 10

# Tablist stats
tab-enabled: true

# Tablist refresh period (in ticks)
tab-refresh-period: 100

